### ISSUE TITLE
Trying to run the example I get

### ISSUE THREAD

**Issue by dk253** [bachya/pytile#13]
Hello,
Thanks for your library!  I am running into trouble though.  I have a brand new ubuntu install.  I installed python 3.6 and your library as well as asyncio and aiohttp.

This is the error I'm getting:

# python3 example.py
Traceback (most recent call last):
  File "tile.py", line 27, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "tile.py", line 16, in main
    await client.async_init()
  File "/usr/local/lib/python3.6/dist-packages/pytile/client.py", line 52, in async_init
    "locale": self._locale,
  File "/usr/local/lib/python3.6/dist-packages/pytile/client.py", line 97, in request
    data=data,
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/client.py", line 502, in _request
    resp = await req.send(conn)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/client_reqrep.py", line 629, in send
    await writer.write_headers(status_line, self.headers)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/http_writer.py", line 111, in write_headers
    buf = _serialize_headers(status_line, headers)
  File "aiohttp/_http_writer.pyx", line 138, in aiohttp._http_writer._serialize_headers
  File "aiohttp/_http_writer.pyx", line 110, in aiohttp._http_writer.to_str
TypeError: Cannot serialize non-str key UUID('f006245f-b9df-45f7-8e63-<not sure if this is private>')

I am pretty new to python so it may be something I am missing.

Thanks!

**Comment by bachya** [comment]
Totally my fault: looks like a bug slipped through https://github.com/bachya/pytile/pull/11. Will fix shortly!

**Comment by bachya** [comment]
[2.0.8](https://github.com/bachya/pytile/releases/tag/2.0.8) and the latest `dev` branch has this fix. Thanks!

**Comment by dk253** [comment]
works great!  Thanks!!
